name = "PAL Title Ending Guard"
application_url = "https://pal-title-trailing-mark-guard-431720136705.vercel.app"
embedded = true
client_id = "ef01f26be3940315d1e04bbea71eb8c5"

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://pal-title-trailing-mark-guard-431720136705.vercel.app/auth/callback",
  "https://pal-title-trailing-mark-guard-431720136705.vercel.app/auth/shopify/callback"
]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/pal-title-trailing-mark-guard/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/pal-title-trailing-mark-guard/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/pal-title-trailing-mark-guard/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/pal-title-trailing-mark-guard/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/pal-title-trailing-mark-guard/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
