name = "PAL Handle Digit Guard"
application_url = "https://pal-handle-digit-tail-guard-431720398849.vercel.app"
embedded = true
client_id = "3db04d0c3a470326a25d8d7c801defb3"

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://pal-handle-digit-tail-guard-431720398849.vercel.app/auth/callback",
  "https://pal-handle-digit-tail-guard-431720398849.vercel.app/auth/shopify/callback"
]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/pal-handle-digit-tail-guard/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/pal-handle-digit-tail-guard/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/pal-handle-digit-tail-guard/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/pal-handle-digit-tail-guard/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/pal-handle-digit-tail-guard/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
