name = "PAL Handle Length Guard"
application_url = "https://pal-handle-length-guard.onrender.com/app"
embedded = true
client_id = "5fd87fbea1bdcd26db5f6236b4356bfa"

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://pal-handle-length-guard.onrender.com/auth/callback",
  "https://pal-handle-length-guard.onrender.com/auth/shopify/callback"
]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
