# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b25b2746b7ca1ee8f6410267d7818c3"
name = "PAL Collection Ratio Guard"
application_url = "https://sleep-threats-bug-mixing.trycloudflare.com"
embedded = false

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://sleep-threats-bug-mixing.trycloudflare.com/auth/callback",
  "https://sleep-threats-bug-mixing.trycloudflare.com/auth/shopify/callback"
]
